[path]
home = "/Users/dylan"
dotfiles = "/Users/dylan/dotfiles"
backup = "/Users/dylan/.dotfiles.bak"

[discovery]
auto_track = false
include = [".config/**/*", ".*", ".*/**/*"]
exclude = [".env*", "!.env.example", ".DS_Store"]

[options]
vcs = "jj"
auto_commit = true
auto_sync = true
auto_sync_interval = "daily"
remote = "git@github.com:dylan-gluck/dots.git"

[experimental]
detect_api_keys = true
